[package]
name = "quick_xml_tree"
version = "0.1.0"
edition = "2018"

[dependencies]
quick-xml = { version = "0.22", features = ["encoding"] }

[dev-dependencies]
criterion = "0.3"
minidom = "0.12"
roxmltree = "0.14"
sxd-document = "0.3"
xmltree = "0.10"
itertools = "0.10"

[[bench]]
name = "bench"
harness = false