[package]
name = "benchmark"

[dev-dependencies]
criterion = "0.3"
minidom = "0.12"
roxmltree = "0.14"
xmltree = "0.10"
xml_dom = ">=0.2.5" # avoid quick-xml version conflict

[[bench]]
name = "bench"
harness = false
