[package]
name = "benchmark"
version = "0.1.0"
edition = "2018"

[dependencies]
xml-doc = {path = "../"}
minidom = "0.12"
roxmltree = "0.14"
xmltree = "0.10"
xml_dom = ">=0.2.5" # avoid quick-xml version conflict
criterion = "0.3"

[[bench]]
name = "bench"
path = "bench.rs"
harness = false
