name: Benchmark

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Benchmark
      run: |
        cd benches
        cargo bench
