name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose 

    - name: Benchmark
      run: |
        cd benches
        cargo bench easyxml
